### ISSUE TITLE
/commands.html and dead links from it

### ISSUE THREAD

**Issue by tnir** [rubygems/bundler-site#536]
There are many dead links from https://bundler.io/commands.html:

- https://bundler.io/bundle_config.html
- https://bundler.io/bundle_exec.html
- https://bundler.io/bundle_gem.html
- https://bundler.io/bundle_package.html
- https://bundler.io/bundle_platform.html
- https://bundler.io/bundle_update.html

`https://bundler.io/commands.html` is at the first in the search results from `https://www.google.com/search?q=bundler+cli` (as of 2020-11-05).

**Comment by deivid-rodriguez** [comment]
Hei! Thanks for reporting this. I have some hesitations about what to do here, because `commands.html` seems like a legacy page no longer linked from anywhere inside the site, and it's also quite confusing because it's styling makes it very hard to match command and applicable options. So, maybe we should get rid of it and redirect to a better page?

**Comment by tnir** [comment]
Until I have to access to https://www.google.com/search?q=bundler+cli, I had the same opinion like you. If permits, do you think I can use redirections all from top-level to `<current_version>/page.html`?

**Comment by deivid-rodriguez** [comment]
What we've been doing lately to play nicer with google is to use `<link href='/man/bundle-config.1.html' rel='canonical'>` from `https://bundler.io/v2.1/man/bundle-config.1.html` an so on, so that google considers them as the same page. However, I'm now observing that we also add canonical refs from `https://bundler.io/v2.0/man/bundle-config.1.html`, which is incorrect since they have different content.

I'm not sure how this plays with https://github.com/rubygems/bundler-site/pull/537.

**Comment by tnir** [comment]
@deivid-rodriguez Thanks for your reply. So do you prefer `/man/bundle-install.1.html` than `https://bundler.io/bundle_config.html`? This issue is different from any pages under `/v2.1/`, `/v2.0` as well as `/man`...

**Comment by deivid-rodriguez** [comment]
I was thinking about redirecting `/commands.html` to some better page (https://bundler.io/docs.html I think would be nice), and I don't think we need to do anything else? Pages like `https://bundler.io/bundle_config.html` don't exist and that seems fine?

**Comment by tnir** [comment]
https://bundler.io/commands.html is still at the second place in the search results from https://www.google.com/search?q=bundler+cli (as of 2022-03-14).

**Comment by deivid-rodriguez** [comment]
Thanks for the ping, I'll try fix this as I suggested previously.

**Comment by deivid-rodriguez** [comment]
https://github.com/rubygems/bundler-site/pull/604 should fix this!

**Comment by tnir** [comment]
Thank you!
